# Generated by Django 4.2.2 on 2023-06-13 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dev_roles', models.CharField(max_length=200)),
                ('lang_pref', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_organization', models.CharField(max_length=200)),
                ('page_hierarchy', models.CharField(max_length=200)),
                ('url_structure', models.CharField(max_length=200)),
                ('branding', models.CharField(max_length=200)),
                ('layout', models.CharField(max_length=200)),
                ('responsive_design', models.CharField(max_length=200)),
                ('visual_elements', models.CharField(max_length=200)),
                ('navigation', models.CharField(max_length=200)),
                ('user_flows', models.CharField(max_length=200)),
                ('form_design', models.CharField(max_length=200)),
                ('accessibility', models.CharField(max_length=200)),
                ('user_authentication', models.CharField(max_length=200)),
                ('user_roles_permissions', models.CharField(max_length=200)),
                ('input_validation', models.CharField(max_length=200)),
                ('attack_protection', models.CharField(max_length=200)),
                ('regular_updates', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='projects.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='projects.structure')),
            ],
        ),
    ]
