# Generated by Django 4.2.2 on 2023-06-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='subject',
            new_name='project',
        ),
    ]
