# Generated by Django 3.2.14 on 2023-06-14 07:50

from django.db import migrations
import projects.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_diversecontent_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='diversecontent',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='diversecontent',
            old_name='diverse_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=projects.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diversecontent',
            name='order',
            field=projects.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
